default_agent: agentcore_starter_strands
agents:
  agentcore_starter_strands:
    name: agentcore_starter_strands
    entrypoint: /Users/sanhehu/Documents/GitHub/aws_bedrock_agent_core_poc-project/docs/source/02-Learn-Bedrock-Agent-Core/agentcore_starter_strands.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/sanhehu/Documents/GitHub/aws_bedrock_agent_core_poc-project/docs/source/02-Learn-Bedrock-Agent-Core
    aws:
      execution_role: arn:aws:iam::361769586364:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-9c0804ec0c
      execution_role_auto_create: false
      account: '361769586364'
      region: us-east-1
      ecr_repository: 361769586364.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentcore_starter_strands
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: agentcore_starter_strands-TOMXiiF4vl
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:361769586364:runtime/agentcore_starter_strands-TOMXiiF4vl
      agent_session_id: 40ec655b-1c1f-41cc-81a4-9098837e1bdf
    codebuild:
      project_name: bedrock-agentcore-agentcore_starter_strands-builder
      execution_role: arn:aws:iam::361769586364:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-9c0804ec0c
      source_bucket: bedrock-agentcore-codebuild-sources-361769586364-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentcore_starter_strands_mem-zkwWWiDDwr
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:361769586364:memory/agentcore_starter_strands_mem-zkwWWiDDwr
      memory_name: agentcore_starter_strands_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
